### ISSUE TITLE
Ringwraiths in Minas Morgul are missing Attack/Wound stat

### ISSUE THREAD

**Issue by Argel-Tal** [Hukoseft/middle-earth-v2-War-of-the-Rohirrim#6]
![Screenshot_20241222_144526.jpg](https://github.com/user-attachments/assets/43dba89a-b69d-41e4-b382-c5e70408f2c7)

Same for Witchking

**Comment by Hukoseft** [comment]
Missing;

Attacks
Might
Will
Fate
Heroic Tier
