### ISSUE TITLE
[Anon] Cirith Ungol: In the Cirith Ungol list, Gorbag's orcs cost 30 points instead of 5


### ISSUE THREAD

**Issue by NewRecruitAnon** [Hukoseft/middle-earth-v2-War-of-the-Rohirrim#8]
**Problem:**
In the Cirith Ungol list, Gorbag's orcs cost 30 points instead of 5

**Expected:**
Change them to 5 points

**List:** https://www.newrecruit.eu/app/list/U1A41

**Comment by Hukoseft** [comment]
This is because New Recruit is by default selecting the banner as Wargear. So adding 25 to the 5 cost. When you add it, you can change the wargear and see how the costs change. The Orc itself is correct at 5 points.
